server:
  port: 8080
  servlet:
    context-path: /myapp

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

myapp:
  custom:
    property: value
